module: AppLaunch
author: IBM
github_url: https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-applaunch

skip_undocumented: true
clean: true

custom_categories:
  - name: Client
    children:
    - AppLaunch